# Generated by Django 5.2.7 on 2025-12-11 12:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import site_telefonie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePachet',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nume_categorie', models.CharField(max_length=100, unique=True)),
                ('durata_minima', models.IntegerField(help_text='Durata minimă în luni')),
                ('icon', models.CharField(blank=True, help_text='Ex: fa-solid fa-wifi', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categorii Pachete',
            },
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id_produs', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=200)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Produse',
            },
        ),
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id_promotie', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.DecimalField(decimal_places=2, help_text='Procent discount (ex: 15.00 pentru 15%)', max_digits=5)),
                ('data_inceput', models.DateField(default=django.utils.timezone.now)),
                ('data_sfarsit', models.DateField(blank=True, null=True)),
                ('descriere_promotie', models.TextField(blank=True, help_text='Descriere opțională a promoției', null=True)),
            ],
            options={
                'verbose_name_plural': 'Promoții',
            },
        ),
        migrations.CreateModel(
            name='UtilizatorPersonalizat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('data_nasterii', models.DateField(validators=[site_telefonie.models.validate_min_age], verbose_name='Data Nașterii')),
                ('adresa', models.CharField(max_length=255, verbose_name='Adresă')),
                ('telefon', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Numărul de telefon trebuie să conțină 10 cifre.')], verbose_name='Număr de Telefon')),
                ('judet', models.CharField(choices=[('AB', 'Alba'), ('AR', 'Arad'), ('AG', 'Argeș'), ('BC', 'Bacău'), ('BH', 'Bihor'), ('BN', 'Bistrița-Năsăud'), ('BT', 'Botoșani'), ('BV', 'Brașov'), ('BR', 'Brăila'), ('B', 'București'), ('BZ', 'Buzău'), ('CS', 'Caraș-Severin'), ('CL', 'Călărași'), ('CJ', 'Cluj'), ('CT', 'Constanța'), ('CV', 'Covasna'), ('DB', 'Dâmbovița'), ('DJ', 'Dolj'), ('GL', 'Galați'), ('GR', 'Giurgiu'), ('GJ', 'Gorj'), ('HR', 'Harghita'), ('HD', 'Hunedoara'), ('IL', 'Ialomița'), ('IS', 'Iași'), ('IF', 'Ilfov'), ('MM', 'Maramureș'), ('MH', 'Mehedinți'), ('MS', 'Mureș'), ('NT', 'Neamț'), ('OT', 'Olt'), ('PH', 'Prahova'), ('SM', 'Satu Mare'), ('SJ', 'Sălaj'), ('SB', 'Sibiu'), ('SV', 'Suceava'), ('TR', 'Teleorman'), ('TM', 'Timiș'), ('TL', 'Tulcea'), ('VS', 'Vaslui'), ('VL', 'Vâlcea'), ('VN', 'Vrancea')], max_length=50, verbose_name='Județ')),
                ('nr_card_implicit', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Numărul de card trebuie să conțină 16 cifre.')], verbose_name='Număr Card Implicit (16 cifre)')),
                ('cnp', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Cod Numeric Personal')),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupuri la care aparține utilizatorul.', related_name='custom_user_groups', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisiuni specifice pentru acest utilizator.', related_name='custom_user_permissions', related_query_name='custom_user_permission', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilizator Personalizat',
                'verbose_name_plural': 'Utilizatori Personalizați',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Serviciu',
            fields=[
                ('produs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='site_telefonie.produs')),
                ('id_serviciu', models.AutoField(primary_key=True, serialize=False)),
                ('descriere_serviciu', models.TextField()),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='servicii/')),
                ('tip', models.CharField(choices=[('telefonie', 'Telefonie mobila'), ('internet', 'Internet fibră optică'), ('cablu', 'TV Cablu')], max_length=50)),
                ('status', models.CharField(choices=[('activ', 'Activ'), ('inactiv', 'Inactiv')], default='activ', max_length=20)),
                ('taxa_activare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Servicii',
            },
            bases=('site_telefonie.produs',),
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('produs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='site_telefonie.produs')),
                ('id_telefon', models.AutoField(primary_key=True, serialize=False)),
                ('descriere_telefon', models.TextField()),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='telefoane/')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('stoc', models.IntegerField(default=0)),
                ('cg_status', models.CharField(choices=[('disponibil', 'Disponibil'), ('indisponibil', 'Indisponibil'), ('comanda', 'La comandă')], default='disponibil', max_length=20)),
                ('cod_imei', models.CharField(help_text='Cod IMEI unic pentru telefon', max_length=15, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Telefoane',
            },
            bases=('site_telefonie.produs',),
        ),
        migrations.CreateModel(
            name='Pachet',
            fields=[
                ('id_pachet', models.AutoField(primary_key=True, serialize=False)),
                ('nume_pachet', models.CharField(max_length=200)),
                ('descriere_pachet', models.TextField(blank=True, null=True)),
                ('data_crearii', models.DateTimeField(auto_now_add=True)),
                ('tip', models.CharField(max_length=50)),
                ('cod_promo', models.CharField(blank=True, help_text='Cod promoțional opțional', max_length=50, null=True)),
                ('apartine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pachete', to='site_telefonie.categoriepachet')),
                ('contine', models.ManyToManyField(help_text='Produse incluse în pachet (servicii și telefoane)', related_name='pachete', to='site_telefonie.produs')),
                ('promotie', models.ForeignKey(blank=True, help_text='Promoție aplicată pachetului (opțional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pachete', to='site_telefonie.promotie')),
            ],
            options={
                'verbose_name_plural': 'Pachete',
            },
        ),
    ]
