# Generated by Django 5.2.7 on 2026-01-03 22:11

import site_telefonie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_telefonie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizatorpersonalizat',
            name='data_nasterii',
            field=models.DateField(blank=True, null=True, validators=[site_telefonie.models.validate_min_age]),
        ),
    ]
