# Generated by Django 5.2.7 on 2026-01-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_telefonie', '0002_alter_utilizatorpersonalizat_data_nasterii'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizatorpersonalizat',
            name='cod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilizatorpersonalizat',
            name='email_confirmat',
            field=models.BooleanField(default=False),
        ),
    ]
