# Generated by Django 5.2.7 on 2026-01-05 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_telefonie', '0003_utilizatorpersonalizat_cod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotie',
            name='mesaj_email',
            field=models.TextField(blank=True, help_text='Mesajul trimis clienților', null=True),
        ),
        migrations.AddField(
            model_name='promotie',
            name='nume',
            field=models.CharField(default='Promotie Generica', max_length=100),
        ),
        migrations.AddField(
            model_name='promotie',
            name='subiect_email',
            field=models.CharField(blank=True, help_text='Subiectul care apare în mail', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promotie',
            name='descriere_promotie',
            field=models.TextField(blank=True, help_text='Descriere internă a promoției', null=True),
        ),
        migrations.CreateModel(
            name='Vizualizare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pachet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_telefonie.pachet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
