# Generated by Django 5.2.7 on 2026-01-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_telefonie', '0004_promotie_mesaj_email_promotie_nume_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produs',
            options={'permissions': [('vizualizeaza_oferta', 'Poate vizualiza oferta specială (banner 50%)')], 'verbose_name_plural': 'Produse'},
        ),
    ]
