# Generated by Django 5.2.7 on 2026-01-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_telefonie', '0005_alter_produs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produs',
            options={'permissions': [('vizualizeaza_oferta', 'Poate vizualiza oferta speciala (banner 50%)')], 'verbose_name_plural': 'Produse'},
        ),
    ]
