# Generated by Django 5.2.7 on 2026-01-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_telefonie', '0006_alter_produs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizatorpersonalizat',
            name='blocat',
            field=models.BooleanField(default=False, verbose_name='Blocat'),
        ),
    ]
