# Generated by Django 5.2.7 on 2026-01-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_telefonie', '0007_utilizatorpersonalizat_blocat'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriepachet',
            name='descriere_categorie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
