# Generated by Django 5.2.7 on 2026-01-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_telefonie', '0008_categoriepachet_descriere_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotie',
            name='categorii',
            field=models.ManyToManyField(help_text='Categorii pentru care se aplică promoția', related_name='promotii', to='site_telefonie.categoriepachet'),
        ),
    ]
